
export const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';

export const SELECT_COUNRTY ='SELECT_COUNTRY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const REQUEST_NEWS = 'REQUEST_NEWS';
export const RECEIVED_NEWS = 'RECEIVED_NEWS';

export const FAILED_TO_FETCH = 'FAILED_TO_FETCH';

export const REQUEST_GITHUB_USERS = 'REQUEST_GITHUB_USERS';
export const RECEIVE_GITHUB_USERS = 'RECEIVE_GITHUB_USERS';

export const SET_DEFAULT_STATE = 'SET_DEFAULT_STATE';
export const RESET_ERROR = 'RESET_ERROR';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const REQUEST_GITHUB_USER_DETAILS ='REQUEST_GITHUB_USER_DETAILS';